import { WorkspaceConnector } from './types';

export const getDefaultWorkspaceConnectors = (): WorkspaceConnector[] => {
  return [
    {
      id: 'github',
      name: 'GitHub',
      key: 'github',
      icon: '🔷',
      description: 'Connect to GitHub repositories and issues',
      enabled: false,
      beta: false,
    },
    {
      id: 'gmail',
      name: 'Gmail',
      key: 'gmail',
      icon: '📧',
      description: 'Access and manage your Gmail messages',
      enabled: false,
      beta: false,
    },
    {
      id: 'google-calendar',
      name: 'Google Calendar',
      key: 'google-calendar',
      icon: '📅',
      description: 'Manage events and meetings',
      enabled: false,
      beta: true,
    },
    {
      id: 'google-drive',
      name: 'Google Drive',
      key: 'google-drive',
      icon: '💾',
      description: 'Access files in Google Drive',
      enabled: false,
      beta: false,
    },
    {
      id: 'jira',
      name: 'Jira',
      key: 'jira',
      icon: '🔷',
      description: 'Manage Jira issues and projects',
      enabled: false,
      beta: true,
    },
    {
      id: 'linear',
      name: 'Linear',
      key: 'linear',
      icon: '⚡',
      description: 'Track Linear issues and projects',
      enabled: false,
      beta: false,
    },
    {
      id: 'microsoft-teams',
      name: 'Microsoft Teams',
      key: 'microsoft-teams',
      icon: '👥',
      description: 'Connect to Teams channels and messages',
      enabled: false,
      beta: true,
    },
    {
      id: 'outlook',
      name: 'Outlook',
      key: 'outlook',
      icon: '📨',
      description: 'Access Outlook emails and calendar',
      enabled: false,
      beta: true,
    },
    {
      id: 'sharepoint',
      name: 'SharePoint',
      key: 'sharepoint',
      icon: '📊',
      description: 'Access SharePoint documents and sites',
      enabled: false,
      beta: true,
    },
    {
      id: 'slack',
      name: 'Slack',
      key: 'slack',
      icon: '💬',
      description: 'Connect to Slack workspaces',
      enabled: false,
      beta: false,
    },
  ];
};
